version: '3.7'
services:
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: eco
        ports:
            - 27017:27017
        expose:
            - 27017
        volumes:
            - mongodb_data_container:/data/db

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        restart: always
        environment:
            ME_CONFIG_MONGODB_AUTH_DATABASE: admin
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
        depends_on:
            - mongo

volumes:
    mongodb_data_container:

